### ISSUE TITLE
Support all valid characters for data object names 

### ISSUE THREAD

**Issue by lwesterhof** [irods/irods_api_plugin_genquery2#51]
- [x] main
- [x] 4-2-stable
---
Queries should support all valid characters for data object names.

Currently a query with some special characters will fail with a -167000 error.

Example query:
`select META_DATA_ATTR_NAME, META_DATA_ATTR_VALUE where COLL_NAME = '/tempZone/home/grp-intake-initial' AND DATA_NAME = '[]{}()#!@$^&,;'%^.txt'`

**Comment by korydraughn** [comment]
See https://github.com/irods/irods_api_plugin_genquery2/pull/68#issuecomment-1716621433 before closing this.

**Comment by korydraughn** [comment]
I think that comment indicates we should consider supporting characters represented in hexadecimal.

**Comment by trel** [comment]
Very interesting.

As long as we don't have to write a new parser... and is documented cleanly, this sounds feasible.
