### ISSUE TITLE
Add Dockerfiles for compiling GenQuery2 for supported platforms

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_api_plugin_genquery2#67]
Platforms
- [x] Ubuntu 18
- [x] Ubuntu 20
- [x] Ubuntu 22
- [x] Debian 11
- [x] Debian 12
- [x] CentOS 7
- [x] EL8
- [x] EL9

The dockerfile must produce a docker image that takes the source directory as a volume mount or the URL of a git repository, build the project, and produce a package for installation.

**Comment by korydraughn** [comment]
After some discussion, we've agreed that introducing a build hook (as seen in the rule engine plugin repos) makes the most sense.

That gives us the ability to take advantage of the development environment and avoids an explosion of Dockerfiles appearing in this repo.

**Comment by korydraughn** [comment]
Yes, please do.

**Comment by alanking** [comment]
Build hook added on both branches. Closing.
