### ISSUE TITLE
`genquery2_sql.hpp` uses `std::vector` but does not `#include <vector>`

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_api_plugin_genquery2#82]
- [x] main
- [x] 4-2-stable

`std::vector` is referenced here:
https://github.com/irods/irods_api_plugin_genquery2/blob/f600cdf88133dfe50114d9db3e7249fc51e12efb/parser/include/irods/genquery2_sql.hpp#L19
but `<vector>` is not `#include`d.
This causes an error during compilation against libstdc++.

**Comment by alanking** [comment]
Looks identical to me:
https://github.com/irods/irods_api_plugin_genquery2/blob/402c276a6c020e8ed0fdbe9658ec2d2bc78d8f2f/parser/include/irods/genquery2_sql.hpp#L19

**Comment by korydraughn** [comment]
Let's add the checkboxes and cherry-pick the change.
